# Generated by Django 3.0.2 on 2020-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.IntegerField(verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('genero', models.CharField(choices=[('M', 'Feminino'), ('F', 'Feminino')], max_length=255, verbose_name='Gênero')),
                ('cargo', models.CharField(choices=[('APRENDIZ', 'Aprendiz'), ('ASSISTENTE', 'Assistente'), ('TÈCNICO', 'Técnico'), ('ANALISTA', 'Analista'), ('Supervisor', 'Supervisor'), ('GERENTE', 'Gerente'), ('DIRETOR', 'Diretor')], max_length=255, verbose_name='Cargo')),
                ('pretencao_salarial', models.FloatField(verbose_name='Pretenção Salarial')),
                ('pcd', models.BooleanField(verbose_name='Possui alguma Deficiência?')),
                ('objetivo', models.TextField(verbose_name='Objetivo Pretendido')),
            ],
        ),
    ]
