# Generated by Django 3.0.2 on 2020-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereço', models.CharField(max_length=255)),
                ('cnpj', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('ramo_de_atividade', models.CharField(choices=[('P', 'publica'), ('PV', 'privado'), ('ONG', 'sem fins lucrativos')], max_length=255)),
                ('porte_tamanho', models.CharField(choices=[('P', 'pequena'), ('M', 'media'), ('G', 'grande')], max_length=255)),
            ],
        ),
    ]
